# This workflow validates Pull Requests
name: PR Validation

# Trigger with every PR to master
on:
  pull_request:
    branches:
      - master

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Code coverage summary report
        uses: ArtiomTr/jest-coverage-report-action@v2

      - name: Run linting
        run: npm run lint
