# This workflow validates Pull Requests
name: PR Validation

# Trigger with every PR to master
on:
  pull_request_target:
    branches:
      - master

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Run tests & generate code coverage summary
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          skip-step: install
